# Generated by Django 6.0.6 on 2026-06-21 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash On Delivery'), ('KHALTI', 'Khalti')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pidx', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('INITIAL', 'Initial'), ('KHALTI_PROCESS', 'Khalti Process'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('USER_CANCELLED', 'User Cancelled')], default='INITIAL', max_length=30)),
                ('location', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
