# Generated by Django 6.0.6 on 2026-06-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('USER_CANCELLED', 'User Cancelled')], default='PENDING', max_length=30),
        ),
    ]
